version: "3"
services:
  paybe_backend:
    container_name: nodejs
    restart: on-failure
    build: ./
    ports:
      - "3040:3040"
    volumes:
      - .:/app
      - ./error.log:/usr/src/app/error.log
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    ports:
    - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: mysql
       MYSQL_USER: root
       MYSQL_DATABASE: test
       MYSQL_PASSWORD: mysql
    volumes:
      - ./data:/data/db